# integration tests for swc ecosystem projects - scheduled or manual run for all suites
name: swc-ecosystem-ci

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

on:
  schedule:
    - cron: "0 5 * * 1,3,5" # monday,wednesday,friday 5AM
  workflow_dispatch:
    inputs:
      refType:
        description: "type of ref"
        required: true
        type: choice
        options:
          - release
        default: "release"
      ref:
        description: "swc version to use"
        required: true
        type: string
        default: "main"
  repository_dispatch:
    types: [ecosystem-ci]
jobs:
  test-ecosystem:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - rollup-plugin-swc3
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
        id: setup-node
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
        id: setup-deno
        continue-on-error: true
      - run: corepack enable
      - run: pnpm --version
      - run: pnpm i --frozen-lockfile
      - run: >-
          pnpm tsx ecosystem-ci.ts
          --${{ inputs.refType || github.event.client_payload.refType || 'release' }} ${{ inputs.ref || github.event.client_payload.ref || 'main' }}
          --repo ${{ inputs.repo || github.event.client_payload.repo || 'swc-project/swc' }}
          ${{ matrix.suite }}
        id: ecosystem-ci-run
      - if: always()
        run: pnpm tsx discord-webhook.ts
        env:
          WORKFLOW_NAME: ci
          REF_TYPE: ${{ inputs.refType || github.event.client_payload.refType || 'release' }}
          REF: ${{ inputs.ref || github.event.client_payload.ref || 'main' }}
          REPO: ${{ inputs.repo || github.event.client_payload.repo || 'swc-project/swc' }}
          SUITE: ${{ matrix.suite }}
          STATUS: ${{ job.status }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
